---
argument_spec:

    ansible_network_os:
      description:
        - Set the name of Ansible network os platform. This value should be
          set to `iosxr` for this provider role.
      required: true

    iosxr_config_text:
      description:
        - Provide the network device configuration as a single string. The
          configuration text will be loaded onto the target network device.
      type: str
      aliases:
        - config_text

    iosxr_config_file:
      description:
        - Provide relative or absolute path to the configuration file to be
          loaded onto the target network device.
      type: str
      aliases:
        - config_file

mutually_exclusive:
  - ['iosxr_config_text', 'iosxr_config_file']

required_one_of:
  - ['iosxr_config_text', 'iosxr_config_file']
